
trigger:
- main

variables:
  vmImageName: 'windows-latest'
  



steps:    
  - script: npm install -g @ionic/cli
    displayName: 'Install Ionic CLI'

  - task: Npm@1
    inputs:
      workingDir: '$(Build.SourcesDirectory)'
      command: install
    displayName: 'NPM Install'

  - powershell: |
      ionic cap build android --prod --no-open
      npx cap sync
      cd android
      ./gradlew assembleRelease
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build Android Project'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksign: true
      apksignerKeystoreFile: keystore-uploadnew.jks
      apksignerKeystorePassword: "Bluebubbles@443"
      apksignerKeystoreAlias: 'keystore-upload'
      apksignerKeyPassword: 'Bluebubbles@443'
      apksignerArguments: --out **/*.apk --verbose
      zipalign: true
    displayName: 'Sign the APK'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '**/*.apk'
      contents: "**/*.apk"
      targetFolder: "$(Build.ArtifactStagingDirectory)"
    displayName: "Copy unsigned APK to staging directory"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "new"
      publishLocation: "Container"
    displayName: "Publish artifacts"

  