
trigger:
- main

variables:
  vmImageName: 'windows-latest'
  



steps:    
  - script: npm install -g @ionic/cli
    displayName: 'Install Ionic CLI'

  - task: Npm@1
    inputs:
      workingDir: '$(Build.SourcesDirectory)'
      command: install
    displayName: 'NPM Install'

  - powershell: |
      ionic cap build android --prod --no-open
      npx cap sync
      cd android
      ./gradlew assembleRelease
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build Android Project'

  