
trigger:
- main

variables:
  vmImageName: 'windows-latest'
  



steps:    
  - script: npm install -g @ionic/cli
    displayName: 'Install Ionic CLI'

  - task: Npm@1
    inputs:
      workingDir: '$(Build.SourcesDirectory)'
      command: install
    displayName: 'NPM Install'

  - powershell: |
      ionic cap build android --prod --no-open
      npx cap sync
      cd android
      ./gradlew assembleRelease
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build Android Project'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '$(Build.SourcesDirectory)/android/app/build/outputs/apk/release/release-1.0.apk'
      apksign: true
      apksignerKeystoreFile: keystore-uploadnew.jks
      apksignerKeystorePassword: "Bluebubbles@443"
      apksignerKeystoreAlias: 'keystore-upload'
      apksignerKeyPassword: 'Bluebubbles@443'
      apksignerArguments: --out $(Build.SourcesDirectory)/android/app/build/outputs/apk/release/release-1.0.apk --verbose
      
    displayName: 'Sign the APK'

  